# Generated by Django 3.2.5 on 2021-09-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_contents',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
    ]
