# Generated by Django 3.2.5 on 2021-09-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0005_alter_table_contents_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_contents',
            name='description',
            field=models.CharField(default='not available', max_length=60),
        ),
        migrations.AlterModelTable(
            name='table_contents',
            table='resharper_crud_database.crud_app_table_contents',
        ),
    ]
