# Generated by Django 3.2.5 on 2021-09-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0006_auto_20210912_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_contents',
            name='description',
        ),
    ]
