# Generated by Django 3.2.5 on 2021-09-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0007_remove_table_contents_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table_contents',
            table=None,
        ),
    ]
